### ISSUE TITLE
Support for ElasticSearch 2.0

### ISSUE THREAD

**Issue by publiux** [spatie/searchindex#15]
Presently, searchindex does not support the ElasticSearch 2.0 library for PHP. Is there a plan to add support for 2.0 while maintaining backwards compatibility with the 1.0 branch, perhaps via a separate branch in the searchindex project?

**Comment by freekmurze** [comment]
We will add ES2 compatiblity when one of our clients requires it. That'll happen sooner or later. If you need this quick, I'd welcome a PR.
