### ISSUE TITLE
SearchIndex::clearIndex() Not Working with Elasticsearch 1.4

### ISSUE THREAD

**Issue by iolson** [spatie/searchindex#16]
I have created a Elasticsearch 1.4 inside my homestead php 7 box. This was done from the [Forge Recipe](http://forgerecipes.com/recipes/70). I have successfully added to the index via the `SearchIndex::upsertToIndex($model);` method. But when I run the following command below its throwing 404 errors when it shouldn't be because I can hit them at localhost:9200/{indexName} without any issues.

``` php
<?php

namespace App\Console\Commands;

use App\Models\Site;
use Elasticsearch\Common\Exceptions\Missing404Exception;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\Config;
use Spatie\SearchIndex\SearchIndexFacade as SearchIndex;

class ClearSearchIndex extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'app:search:clear';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Clear search index.';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $index = Config::get('searchindex.elasticsearch.defaultIndexName');
        $sites = Site::all('full_domain');

        try {
            SearchIndex::clearIndex();
            $this->info("Cleared search index for: {$index}");
        } catch (Missing404Exception $e) {
            $this->comment("Index: {$index} not found.");
        }

        foreach($sites as $site) {
            Config::set('searchindex.elasticsearch.defaultIndexName', $site->full_domain);
            try {
                SearchIndex::clearIndex();
                $this->info("Cleared search index for: {$site->full_domain}");
            } catch (Missing404Exception $e) {
                $this->comment("Index: {$site->full_domain} not found.");
            }
        }
    }
}
```

Was wondering if this is an issue on my end, or something that is an issue with the library. This is the following output that I get from doing the CLI command: https://www.dropbox.com/s/0t9bur06cl5dxt2/Screenshot%202016-03-31%2015.19.09.png?dl=0

**Comment by freekmurze** [comment]
I'm thinking that it should work on 1.4, but it's been a while since I used
this package myself. There's a project coming up in a few weeks that'll
need Elasticsearch. I'll test it out then. If you find a solution
meanwhile, let me know.

**Comment by sebastiandedeyne** [comment]
Gonna close this since it's been inactive for quite a while. Feel free to reopen if this needs attention again!
