### ISSUE TITLE
Specify index in given query/upsert

### ISSUE THREAD

**Issue by harrygr** [spatie/searchindex#18]
Currently it is possible to set the default index to use (either for Algolia or ES) in the searchindex config. I noticed this block:

```
/*
 * This index will be used whenever you don't explicitly
 * set one yourself.
 */
'defaultIndexName' => 'main',
```

There is nothing in the docs explaining how to "explicitly set one yourself" aside from in the config. Is this possible? E.g. `\SearchIndex::upsertToIndex($product, 'products');`. Could one update the config value at runtime? although I suppose the SearchIndex class in instantiated when the app is booted so will ignore any subsequent config value change.

It would be nice to be able to specify which index to upsert/query to/from. Or would one normally have all records in the same index and filter out the ones not relevant? E.g. products/posts. Ideally this would be driver agnostic (e.g. work the same way for ES and Algolia).

**Comment by freekmurze** [comment]
You can use the `setIndexName`-function: 

``` php
SearchIndex::setIndexName($nameOfIndex);
```

This will work with both the Algolia and Elasticsearch driver. From then on all calls to `SearchIndex` will use that index name.

It depends on the use case, but if you only have simple products and posts and store them in the same index and add a `type`-field.
