### ISSUE TITLE
Laravel 5.2 - Class searchIndex does not exist

### ISSUE THREAD

**Issue by apstyx** [spatie/searchindex#22]
Hi, I have a L5.2 application and all seems to be correctly configured. 

When I try to 
`
SearchIndex::upsertToIndex($createdModel);
`

With the following use specified

`
use Spatie\SearchIndex\SearchIndexFacade as SearchIndex;
`

I get the error: **Class searchIndex does not exist**

Any suggestions of obvious things I may have missed?

**Comment by freekmurze** [comment]
Try replacing `use Spatie\SearchIndex\SearchIndexFacade as SearchIndex;` by `use SearchIndex`. Reopen this issue if you're still getting errors.
