### ISSUE TITLE
[proposal] Add indexExists Method to Elasticsearch

### ISSUE THREAD

**Issue by Naoray** [spatie/searchindex#28]
Could we add a private `indexExists()` method inside the `ElasticSearch` - handler and adjust `clearIndex()` like this:

```php
public function clearIndex($indexName = null)
{
    $indexName = $this->resolveIndexName($indexName);

    if (! $this-indexExists($indexName)) {
        return;
    }

    $this->elasticsearch->indices()->delete(['index' => $indexName]);
 }
```

Cause the underlying ElasticSearch `Client` just throws an exception if there is no index to clear.

Another possible implementation would be to allow setting an `ignore` parameter and pass this one along with the `index` into the delete request.

What do you think?

**Comment by freekmurze** [comment]
> Cause the underlying ElasticSearch Client just throws an exception if there is no index to clear.

Users of this package may rely on the current behaviour. Just write a try/catch block around the `clearIndex` method.

**Comment by Naoray** [comment]
already did, just thought it might be useful for other users too.
