### ISSUE TITLE
Elastic version 6

### ISSUE THREAD

**Issue by kossa** [spatie/searchindex#30]
Hello,
Currently spatie/searchindex uses version 2 of elasticSearch, there is a way to use version 6 ?

Thanks

**Comment by brendt** [comment]
Yes, I PR'd a small change a few weeks ago which allows you to specify an index name when you're upserting or removing stuff from the index: https://github.com/spatie/searchindex/pull/27/files

In ES 6, multiple types per index aren't allowed anymore. So if you want to index multiple things, you can use a manually specified index name:

```php
$this->elastic->upsertToIndex($model, $indexName);
```
Are there any other problems occurring with newer versions that you're aware of?

**Comment by kossa** [comment]
So here : https://github.com/spatie/searchindex#elasticsearch I'll install latest version of Elastic (6) ?

**Comment by brendt** [comment]
@kossa yes, that's also what I did. I haven't taken the time yet to update the README, but I'll add it as an issue.

**Comment by MarkVilludo** [comment]
Class 'Spatie\\SearchIndex\\Query\\Algolia\\SearchIndex' not found how to solve this issue?

always having an error when include this use Spatie\SearchIndex\Query\Algolia\SearchIndex();
