### ISSUE TITLE
Re-indexing an entire Model

### ISSUE THREAD

**Issue by dingman** [spatie/searchindex#32]
Hi! TIA for a great package, looking forward to using it.

I didn't see any documentation around reindexing an entire model. I recently added the package, but I now want to get my entire model into the index.

Any suggestions how to do that?

**Comment by freekmurze** [comment]
There's an example in the readme: https://github.com/spatie/searchindex#update-an-object-in-the-index

**Comment by dingman** [comment]
HI @freekmurze oh great, thank you.

I'm reading it, but I'm still not clear how to reindex an entire model. Is there another example you can share? thank you!
