### ISSUE TITLE
TO add

### ISSUE THREAD

**Issue by marijang** [spatie/searchindex#5]
Can you implement parameter or add method in trait for creating index settings?
for exp

http://blog.qbox.io/quick-and-dirty-autocomplete-with-elasticsearch-completion-suggest

for exp via method 
getSearchableSettings()

Thanks

**Comment by freekmurze** [comment]
Version 3 of this package adds a function to get the underlying client:

``` php
SearchIndex::getClient(); // will return the Elasticsearch or Algolia client.
```

What this client you can do any operation you want.
