### ISSUE TITLE
For newbies

### ISSUE THREAD

**Issue by inanmadak** [spatie/searchindex#8]
I want to ask another question, what is default index name created by SearchIndex? And how to use it with url api of elastic search? Since I am also kind of new to laravel and elastic search, will you add some kind of mapping functionality like this one : https://github.com/adamfairholm/Elasticquent (because elastic queries seems quite hard ) if it is possible to apply these functions in the mentioned package how can i do that? thanks.

**Comment by freekmurze** [comment]
You can see in the config file that the default index name for elasticsearch is main
https://github.com/spatie/searchindex/blob/master/resources/config/searchindex.php#L36

I'm not planning on adding a mapper myself as I don't need this now in my projects. But I'll happily accept any PR that adds it.
